package ring.world;

import java.util.*;

/**
 * Represents an event generated by the world ticker.
 * @author projectmoon
 *
 */
public class TickerEvent extends EventObject {
	private static final long serialVersionUID = 1L;
	
	private int currentTick;
	private String tickID;

	public TickerEvent(Object source, int currentTick, String tickID) {
		super(source);
		this.currentTick = currentTick;
		this.tickID = tickID;
	}

	public int getCurrentTick() {
		return currentTick;
	}

	public String getTickID() {
		return tickID;
	}
}